version: "3.9"
services:
    trainsim-user-service:
        image: maven:3.8.1-openjdk-11
        command: mvn exec:java -pl trainsim-user-service
        working_dir: /source
        volumes:
            - .:/source
            - .m2:/root/.m2
        ports:
            - 8002:80
        environment:
            MAVEN_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1044
            DB_URL: jdbc:postgresql://trainsim-user-db:5432/trainsim-user
            DB_USER: user
            DB_PASSWORD: password
        depends_on:
            - trainsim-user-db
    trainsim-user-db:
        image: postgres:13
        environment:
            POSTGRES_DB: trainsim-user
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ./trainsim-user-db/data:/var/lib/postgresql/data
            - ./trainsim-user-db/scripts:/docker-entrypoint-initdb.d:ro
